const TIMER_INTERVAL = 1000;
const MAX_TIMER = 10;
const MIN_RANDOM_NUMBER = 1;
const MAX_RANDOM_NUMBER = 100;
const MULTIPLE_THREE = 3;
const MULTIPLE_FIVE = 5;
const RESET_BINGO = 4;

export {
  TIMER_INTERVAL,
  MAX_TIMER,
  MIN_RANDOM_NUMBER,
  MAX_RANDOM_NUMBER,
  MULTIPLE_THREE,
  MULTIPLE_FIVE,
  RESET_BINGO,
};
