version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  backend:
    image: node:lts
    container_name: backend
    restart: on-failure
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: project_db
      APP_PORT: 3001
      JWT_SECRET: secret
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bash -c "chgrp -R node /root && chown -R node /root && bash"

