version: "3.8"

services:
  backend:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3001:3001
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: test
      DB_HOST: db
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
